#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xBB5869F064EA74AB (chet@cwru.edu)
#
Name     : readline
Version  : 7.0
Release  : 1
URL      : http://mirrors.kernel.org/gnu/readline/readline-7.0.tar.gz
Source0  : http://mirrors.kernel.org/gnu/readline/readline-7.0.tar.gz
Source99 : http://mirrors.kernel.org/gnu/readline/readline-7.0.tar.gz.sig
Summary  : Gnu Readline library for command line editing
Group    : Development/Tools
License  : GPL-3.0
BuildRequires : ncurses-dev
BuildRequires : ncurses-dev32
Patch1: 0001-Defaultinput-meta-output-meta-to-on.patch
Patch2: cve-2014-2524.nopatch
Patch3: 0001-Support-stateless-inputrc-configuration.patch
Patch4: build.patch
Patch5: readline-6.2-shlib.patch
Patch6: tinfow.patch

%description
Introduction
============
This is the Gnu Readline library, version 7.0.
The Readline library provides a set of functions for use by applications
that allow users to edit command lines as they are typed in.  Both
Emacs and vi editing modes are available.  The Readline library includes
additional functions to maintain a list of previously-entered command
lines, to recall and perhaps reedit those lines, and perform csh-like
history expansion on previous commands.

%prep
%setup -q -n readline-7.0
%patch1 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1546883517
export CFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static --with-curses --enable-multibyte
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1546883517
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/readline
cp COPYING %{buildroot}/usr/share/package-licenses/readline/COPYING
%make_install

%files
%defattr(-,root,root,-)
